### ISSUE TITLE
If contentful doesn't have the data, don't raise an exception

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/wcc-contentful#1]
https://app.bugsnag.com/watermark-community-church/theporch/errors/5a871b067df9d00019e2740b?event_id=5a871b067df9d00019e2740a&i=em&m=nw

**Comment by rorJeremy** [comment]
I'm not able to view the link to the error in bugsnag, are you? I don't remember what this was referencing to answer your question. @gburgett

**Comment by gburgett** [comment]
I think it's done - `WCC::Contentful::Model.find` returns null if it's not there.
