### ISSUE TITLE
Make Favicons/Theme stuff in gem

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/wcc-contentful#10]
There oughta be a "site theme" content type like on JTJ which has at minimum favicons.

There needs to be a readme doc that we can point the arts team to which defines the required icon sizes, filenames, file formats, & other conventions

**Comment by frizman21** [comment]
Mike to understand requirements for WMR.com

**Comment by jpowell** [comment]
@gburgett site configs are specific enough that we wouldn't want to codify them in the gem, right?

**Comment by gburgett** [comment]
I think so
