### ISSUE TITLE
Which content types needs re-work to ...

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-contentful#106]
Adhere to the Bootstrap only, no inline CSS rule?

**Comment by gburgett** [comment]
Easiest way to do this is to finish https://github.com/watermarkchurch/paper-signs/issues/48 first

**Comment by gburgett** [comment]
https://github.com/watermarkchurch/paper-signs/issues/55
https://github.com/watermarkchurch/paper-signs/issues/54
https://github.com/watermarkchurch/paper-signs/issues/52
