### ISSUE TITLE
Implement preview in the gem

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/wcc-contentful#113]
Here's the current code in the pages controller:

```ruby
@page = WCC::Contentful::Model::Page.find_by(slug: slug, options: { include: 3 })
```

Determine the best way to enable previews for the wcc-contentful-app gem, and implement it.
Options:
* Expect the app's ApplicationController to define a `use_preview?` method
* Have a configuration parameter which sets the preview password & check that param in pages/show
* Some other configurable option?

**Comment by frizman21** [comment]
@gburgett This feels like an accessory, not critical for the launch. Feel free to punt.
