### ISSUE TITLE
Consider allowing hooks for instrumentation on client events

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/wcc-contentful#114]
- cache read / fetch / hit / miss
- cdn queries
- maybe others?

Could implement as a middleware so that it works no matter the store configured... Consider libraries like:
- [Rails Notification](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html)
- [Riemann](https://github.com/riemann/riemann-ruby-client)

**Comment by gburgett** [comment]
fixed in https://github.com/watermarkchurch/wcc-contentful/pull/188
