### ISSUE TITLE
Skin / Style UX

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-contentful#147]
The dropdown lists for skin, style, and mode should be:
- not a required field
- there's a default behavior when the field isn't selected
- the default behavior is an option in the list
- all other behaviors are listed as a field.

The intent is that the user doesn't have to make a selection and the default behavior happens.
If they make a selection, default is one of the options. "unset" is valid, but not an intuitive choice.

If/when contentful support default values, (or we're willing to write the UI Extension to make this happen) we would make it required and pre-select the value.

**Comment by gburgett** [comment]
Will not fix in gem - rather will do in app
