### ISSUE TITLE
Handle "Response size too big" errors from Contentful

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/wcc-contentful#161]
According to a thread I was following in the Contentful slack:

> tim [1 day ago]
> It might be that the total response is too large.
> I believe the current limit is 7MB of response size before the API responds with 400.
> The API itself also responds with an explicit error message, so I assume it somehow got lost somewhere in the SDK or gatsby

> Gordon Burgett [1 day ago]
> Hey Tim, do you have any documentation on that error message?  We haven’t seen it yet but we want > to be sure we handle it properly when we start adding multiple locales

> tim [1 day ago]
> It'll be a `400` with the message `BadRequest: Response size too big, was: Xb. Maximum allowed response size: 7340032b.`

How should we handle this?  Can we do so automatically?

**Comment by jpowell** [comment]
@gburgett This already handled? Haven't seen errors like this in a long time.

**Comment by gburgett** [comment]
I don't think we've run into this on our site.  It could be a problem if we go multilingual with a lot of text though.

**Comment by gburgett** [comment]
Let's not do anything automatically with this.  If people run into this they can fine tune their `include:` params.
