### ISSUE TITLE
Approved for publishing now, publish in the future

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-contentful#21]
Use case: As a communications admin, I want to preload the easter service days/times into the CMS. I want those to be published at 8pm the Sunday before the passion week. I don't want to have to login on Sunday to make this happen.

![image.png](https://zube.io/files/watermarkchurch/e3dc26c93e21a87f0e8a6ab923ecb41a-image.png)

This capability needs to exist for just about everything in the CMS. Feels like something that should be core to the infrastructure.

**Comment by gburgett** [comment]
Exit criteria:
* Implemented somewhere
* Code is in the gem & working for slugs/menus

https://github.com/contentful/contentful-scheduler.rb ?

**Comment by frizman21** [comment]
This is now a research task. Output - write a card with how to pull this off.
Team meeting to discuss the output of the research.

**Comment by frizman21** [comment]
(1) Proxy that understand current state
(2) Investigate if you can get previous versions from the API.
(3) Leave entries in unpushblished until content-scheduler pops it up.
(4) Ask Contentful about publishing in the future.

**Comment by gburgett** [comment]
Contentful has now implemented this in their content editing UI.
