### ISSUE TITLE
Research: adding support for native cross-space linking

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/wcc-contentful#275]
### What would we like to understand further?
What is needed to implement cross-space link support in the gem?

### Deliverables / Questions to Answer
- What's needed to get cross-space link support added to the gem?
- Do we need to update any UI extensions?
- Are there any limitations?
- Can we build a drop-in replacement for the existing solution we've build using UI extensions?

### Timebox
4 hours

### Who to report findings to
Gordon

**Comment by gburgett** [comment]
Cross-space referencing requires the "orchestration" feature, which is available in the "Premium" tier.
![image.png](https://zube.io/files/watermarkchurch/d68b78b0ee821cac5f2ceded55a357c4-image.png)

We are currently on the "Enterprise" tier, which appears to be a negotiated tier that Contentful doesn't offer anymore.
