### ISSUE TITLE
Site Wide Announcement

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-contentful#29]
MVP:
- [ ] Text + CTA to a link
- [ ] Should be a contentful gem implementation - available to all other sites (e.g., watermark.org, watermarkresources.com)

Use case: 
* Announce a price change
* Announce an upcoming conference

Later:
- [ ] Can be scheduled regularly or one-time in the future.
- [ ] Can be all campus.
- [ ] Can be campus specific.

**Comment by frizman21** [comment]
does wmr.com need this?

**Comment by gburgett** [comment]
This card is currently in the Gem's repository.  I feel that this feature as it exists in Paper Signs is not mature enough to move into the Gem (it still uses cron syntax - not ideal.)

There's room for a competing implementation in WMR that we do independently, then come back & compare and bring the best parts into the gem.
