### ISSUE TITLE
expand preview find capabilities to find using id

### ISSUE THREAD

**Issue by rorJeremy** [watermarkchurch/wcc-contentful#31]
Right now you can use the preview_client is only compatible with 'find_by'. So you can search using a content type, but we want to also be able to do a find with the preview_client using just the id of a record in contentful. This will help especially for when something like a Blog Post that has links to other tables in Contentful. For example, Blog Post links to Author. Well when you do a BlogPost.find_by you will get a blog object, but if Author has some updated changes that haven't been published, you won't see those changes reflected in the Blog Post you just received, even if you use the preview_client as it is today. This is because the BlogPost object comes back only with an id that points to the Author, and since we can't use preview_client for any id searches, it will only find the published stuff.

**Comment by gburgett** [comment]
I believe this works now
