### ISSUE TITLE
Handle rate limits and 503 service unavailable from Contentful CDN

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/wcc-contentful#37]
https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/api-rate-limits

The gem should handle the following response at the SimpleClient level:
```
HTTP/1.1 429
X-Contentful-RateLimit-Reset: 1
```

The gem should then block all threads from making new queries until the reset period has elapsed.  The request that caused the `429` response should also be retried.

**Comment by gburgett** [comment]
While we're at it we should also automatically retry on 503s, which we seem to get occasionally in JTJ

**Comment by gburgett** [comment]
@frizman21  https://app.bugsnag.com/watermark-community-church/paper-signs/errors/5d83f724d818e100196d61d7?event_id=5d83f7240050405a411d0000&i=sk&m=nw

Happened in fort-worth environment today

**Comment by frizman21** [comment]
Please investigate.

**Comment by gburgett** [comment]
Oh man this is probably them tooting around in preview mode!  We totally skip the cache in preview mode and always hit the CDN directly.  We can optimize this...
