### ISSUE TITLE
Initialization process

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/wcc-contentful#55]
A block of this nature can go in an initializer or config if you're not using rails.

```
WCC::Contentful.configure do |config|
  # Required
  config.access_token = ENV['CONTENTFUL_ACCESS_TOKEN']
  config.space = ENV['CONTENTFUL_SPACE_ID']

  # Optional
  config.environment = ENV['CONTENTFUL_ENVIRONMENT']
  config.management_token = ENV['CONTENTFUL_MANAGEMENT_TOKEN']

  # config.default_locale = # Set default locale, if left blank this is 'en-US'
  # config.content_delivery = :eager_sync
  # config.sync_store = # :memory, :postgres, or a custom implementation

  # config.webhook_username = 'test'
  # config.webhook_password = 'supersecret'

  config.webhook_jobs << AlgoliaSyncJob
end

# Download content types, build models, and sync content
WCC::Contentful.init!

# Validate that models conform to a defined specification
# WCC::Contentful.validate_models! unless defined?(Rails) && Rails.env.development?
```

/cc @reidcooper - would love any feedback you have

**Comment by reidcooper** [comment]
@jpowell I would suggest at least adding the configuration options to the README and/or to the generator. For example, I didn't even know I could use "content_delivery" without diving into the code.

**Comment by jpowell** [comment]
Sweet! We've been using this internally, and are actively developing conventions around how we use contentful as we spin up multiple apps. Since it's been internal, the docs are coming along more slowly. We do have some docs at www.rubydoc.info/github/watermarkchurch/wcc-contentful

The reasons for building this was our needs around using contentful in production (cache invalidation, webhook management, etc), ease of use and extensibility from an individual app implementation standpoint.

I'm in the contentful slack organization if you'd like to shorten the feedback loop.

**Comment by reidcooper** [comment]
@jpowell Do you have a quick link for the contentful slack? It would be better to chit chat that way.

**Comment by jpowell** [comment]
https://www.contentful.com/slack/

**Comment by gburgett** [comment]
Hi @reidcooper !  I'm also happy to answer any of your questions.  Ping me on the contentful slack if you need anything.
