### ISSUE TITLE
Supporting side-by-side with contentful broken

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/wcc-contentful#57]
https://github.com/watermarkchurch/wcc-contentful/blob/master/lib/wcc/contentful.rb#L83

Need:
- [ ] regression test for supporting `Contentful` library namespace
- [ ] fix require statement to specify correct file location (since some things moved around)

**Comment by gburgett** [comment]
This is fixed now - we no longer directly rely on any Contentful namespaced code
