### ISSUE TITLE
Create built-in test that validates the Contentful data structure

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/wcc-contentful#6]
Built in test should:
* Run on initialize
* Download content types for Page, Menu, Redirect/Slug, etc.
* Raise error if any required fields are missing or not of the expected type

Built in test might:
* Run on "find" if it hasn't been run in a while (e.g. 24 hrs)
* Be configurable by requiring some .rb file in the app for each content type

**Comment by jpowell** [comment]
@gburgett this done with `validate_models`?

**Comment by gburgett** [comment]
Yep!
