### ISSUE TITLE
Sync Job Fails to Execute after the initial Sync

### ISSUE THREAD

**Issue by reidcooper** [watermarkchurch/wcc-contentful#62]
Seems that when the sync job tries to sync an additional time, it fails due to a `JSON.parse` error with the `sync:token` that is saved to the database.

`raw['nextSyncUrl'] = "https://cdn.contentful.com/spaces/hchhdjhlmvsi/environments/master/sync?sync_token=w5ZGw6JFwqZmVcKsE8Kow4grw45QdyZ-w4NtwrRKw44qOFpfw6fCucOhBMOjTMKOwqUdG8K5a3MpwrzCsB7DtATDplVWwo7Cn8OGw71PwqFLAcKNw5bCq8KHwrwOw6hZM8KeecOOAx1bbQM-S0hIw71wwq4"`

That does not look like JSON to me and it fails when the code performs the `#find` on the Postgres store.

```
def find(key)
      result = @conn.exec_prepared('select_entry', [key])
      return if result.num_tuples == 0
      JSON.parse(result.getvalue(0, 1))
end
```

Postgres Store
```
def find(key)
   36:       result = @conn.exec_prepared('select_entry', [key])
   37:       return if result.num_tuples == 0
=> 38:       JSON.parse(result.getvalue(0, 1))
   39:     end
```

`result.getvalue(0, 1) = "\"w5ZGw6JFwqZmVcKsE8Kow4grw45QdyZ-w4NtwrRKw44qOFpfw6fCucOhBMOjTMKOwqUdG8K5a3MpwrzCsB7DtATDplVWwo7Cn8OGw71PwqFLAcKNw5bCq8KHwrwOw6hZM8KeecOOAx1bbQM-S0hIw71wwq4\""`

Sentry.io error link: https://sentry.io/share/issue/dd91cda236cb479c9eda293362ebf293/

**Comment by gburgett** [comment]
I think this was fixed in #63
