### ISSUE TITLE
How to hook in to A/B testing?

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/wcc-contentful#8]
Research and determine some consistent way across all sites that we can do A/B testing with contentful objects.  The solution should:

* Provide some interface by which an admin can set up an A/B test
* The admin can select multiple pieces of data from contentful (are these separate objects? 2 different fields in the same object?  Some other format?)
* The admin can see the results of the test and implement one of the options permanently.
* The non-selected option is removed from contentful (manual process? Automatic via management API?)

**Comment by skipperpickle** [comment]
Using VWO now.
https://app.vwo.com/#/dashboard
