### ISSUE TITLE
SEO meta tag contentful section

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-contentful#93]
Assumes that every page include a title.
- [ ] App should automatically populate the canonical link on all pages, by default - what do we think the URL to this page is.
- [ ] provide a field for everything in this list
https://github.com/kpumuk/meta-tags#allowed-options-for-display_meta_tags-and-set_meta_tags-methods
- can assume that application.rb fires display_meta_tags function call and include this gem
meta-tags in the gem file
- consider which of these are common answers on every page - create object structure to represent this complexity - require CMS implementor to only provide page specific details

**Comment by gburgett** [comment]
Moved to doing this in each app, not in the gem
